# For more information, see: https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-3.7

# Local packages, usually specified by relative directory name
packages:
- '.'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: [
    # for midi
    haskore-0.2.0.7
  , event-list-0.1.1.2
  , markov-chain-0.0.3.3
  , midi-0.2.1.5
  , non-negative-0.1.1
  , utility-ht-0.0.11
  , explicit-exception-0.1.7.3
  , monoid-transformer-0.0.3
  , data-accessor-0.2.2.6
]

# Override default flag values for local packages and extra-deps
flags: {}

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 0.1.4.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
